import Head from 'next/head';

import { Sidebar } from '../components/layout/Sidebar/Sidebar';
import styles from '../styles/Home.module.css';

import type { NextPage } from 'next';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </div>
  );
};

export default Home;
